### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by slarrain** [TkTech/ckanext-cloudstorage#18]
I can upload a resource and it is saved on S3 correctly (I can go to S3 and the file is downloadable from S3). However, if I try to download the file from CKAN, I get an "Internal Server Error".

On the log files, I found this:
```
[Sat Aug 12 23:55:24.205323 2017] [:error] [pid 25533:tid 139768329168640] [remote 127.0.0.1:10852] File '/usr/local/lib/python2.7/dist-packages/ckanext_cloudstorage-0.1.1-py2.7.egg/ckanext/cloudstorage/controller.py', line 53 in resource_download
[Sat Aug 12 23:55:24.205325 2017] [:error] [pid 25533:tid 139768329168640] [remote 127.0.0.1:10852]   base.redirect(uploaded_url)
[Sat Aug 12 23:55:24.205327 2017] [:error] [pid 25533:tid 139768329168640] [remote 127.0.0.1:10852] AttributeError: 'module' object has no attribute 'redirect'
```

And indeed, the `base.py` from [ckan](https://github.com/ckan/ckan/blob/master/ckan/lib/base.py) doesn't have any `redirect`. It [used to](https://github.com/ckan/ckan/blob/71f9892a24df1d2f3797054fa1a40c223d2d84eb/ckan/lib/base.py), but then it got [removed](https://github.com/ckan/ckan/commit/34f3f18e8893b5fc33047df94c88d4852c9a1f6b#diff-0aa5b9638fa87bb9c7fa9bca15b2c0db) a month after the last time the `controller.py` was updated.

It looks to me like a critical bug, but I do not have enough ckan experience to propose a PR to fix it, unfortunately.

I'm using ckan2.7 on Ubuntu 14.04

**Comment by TkTech** [comment]
You're using a release that came out a few days ago and includes breaking changes. It's an easy fix.

**Comment by slarrain** [comment]
Indeed, your commit fixes the problem. Thank you so much for the quick fix @TkTech

**Comment by TkTech** [comment]
No problem, thank you for reporting it! We're stuck on a fairly old version at the moment so I don't notice issues like these.
