### ISSUE TITLE
Unclear Documentation regarding Installation and Code

### ISSUE THREAD

**Issue by hamza7292** [TkTech/ckanext-cloudstorage#37]
I find somethings not very clear in the documentation, specially for a newbie like me. 

First is the installation process.
- I cloned the repo and run 
`$ python setup.py install`

Now where to add the following lines of code.

`ckanext.cloudstorage.driver = S3 `
`ckanext.cloudstorage.container_name = my_bucket_name`

I added them in the  "/etc/ckan/default/development.ini" file. Sadly did not work for me.

Secondly for
`ckanext.cloudstorage.driver_options = {"key": "<your public key>", "secret": "<your secret key>"}`
Are these supposed to be my IAM User Public Access and Secret Access Keys or are these some other keys. Furthermore is this also going to go in development.ini

Thanks

**Comment by TkTech** [comment]
Covered by general documentation issue #44
