### ISSUE TITLE
S3 Driver for ca-central-1 region

### ISSUE THREAD

**Issue by ChildOfJustice** [TkTech/ckanext-cloudstorage#46]
Good day for you!
Can you tell me please, how can I correctly choose the name of the driver for the CANADA region in AWS S3.
I can use many other drivers, like this for example:

(/etc/ckan/default/production.ini):
ckanext.cloudstorage.driver = S3_EU_WEST

But when I'm trying to use the name "S3_CA_CENTRAL", I have this:
ERROR: AttributeError: type object 'Provider' has no attribute 'S3_CA_CENTRAL'

And I cannot figurate out, from where do you use these names? There is no such in libcloud docs: https://libcloud.readthedocs.io/en/stable/_modules/libcloud/storage/drivers/s3.html?highlight=region%20s3#

Do I just need a right name of the driver? Or there is no way to use buckets from ca-central-1 region?

Thank you in advice.

**Comment by TkTech** [comment]
You're most likely using the master version of the project, which is still on [libcloud 1.5](https://github.com/TkTech/ckanext-cloudstorage/blob/master/setup.py#L21), but you're using the documentation for version 3. Use https://libcloud.readthedocs.io/en/v1.5.0/_modules/libcloud/storage/drivers/s3.html instead. It's not too difficult to update, but someone needs to take the time to do it.

There is a libcloud2 branch, https://github.com/TkTech/ckanext-cloudstorage/tree/libcloud2.
