### ISSUE TITLE
DataExplorer doesn't work with private S3 resources

### ISSUE THREAD

**Issue by frostygrizzly** [TkTech/ckanext-cloudstorage#7]
In case of private resources DataExplorer View doesn't show data from these resources. At the same it's possible to download resource file (.csv) so links are valid.

![screen shot 2016-10-31 at 8 21 33 pm](https://cloud.githubusercontent.com/assets/3992793/19866512/18d14d42-9fa9-11e6-9a0f-b94aae39d184.png)

DataExplorer works well if we mark resource as Public.

**Comment by TkTech** [comment]
I will try to take a look at this during the week, however heads up that the DataProxy is unsupported and thus remote DataExplorer views are as well.

**Comment by andreysabitov** [comment]
I've also tested with the next S3 CORS configuration:
```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
``` 
but it didn't help

**Comment by rhunwicks** [comment]
I think that this is caused by https://github.com/ckan/datapusher/issues/116.

**Comment by rhunwicks** [comment]
Also, the trunk version of datapusher no longer has the problem.

**Comment by TkTech** [comment]
Resolved upstream.

**Comment by rubberduck203** [comment]
@TkTech do you have any more information about how this was resolved upstream?
